import { getCoreLabels } from './localization.js';
import { ELEMENT_CODES } from './constants.js';
const localizedPillar = (stemCode, branchCode, locale) => { const labels = getCoreLabels(locale), stem = labels.stems[stemCode], branch = labels.branches[branchCode]; return { stemCode, stem, branchCode, branch, text: `${stem} ${branch}` }; };
const chartPillar = (pillar, locale) => { const labels = getCoreLabels(locale), base = localizedPillar(pillar.stem.code, pillar.branch.code, locale), label = { vi: { YEAR: 'Năm', MONTH: 'Tháng', DAY: 'Ngày', HOUR: 'Giờ' }, en: { YEAR: 'Year', MONTH: 'Month', DAY: 'Day', HOUR: 'Hour' } }[locale][pillar.labelCode], tenGod = pillar.tenGodCode === 'DAY_MASTER' ? (locale === 'en' ? 'Day Master' : 'Nhật Chủ') : labels.tenGods[pillar.tenGodCode]; return { ...base, labelCode: pillar.labelCode, label, tenGodCode: pillar.tenGodCode, tenGod }; };
/** Build an AI-friendly localized summary without mutating the canonical chart. */
export function localizeChartSummary(chart, locale = 'vi') {
    const labels = getCoreLabels(locale), active = chart.luck.active.pillar, primaryTenGodCode = chart.pillars.month.branch.hiddenStems[0].tenGodCode, strengthCodes = { khuyết: 'MISSING', yếu: 'WEAK', 'trung bình': 'BALANCED', vượng: 'STRONG' }, strengthLabels = { vi: { MISSING: 'khuyết', WEAK: 'yếu', BALANCED: 'trung bình', STRONG: 'vượng' }, en: { MISSING: 'missing', WEAK: 'weak', BALANCED: 'balanced', STRONG: 'strong' } }, dmStrengthCodes = { 'thân nhược': 'WEAK', 'trung hòa': 'BALANCED', 'thân vượng': 'STRONG' }, dmStrengthLabels = { vi: { WEAK: 'thân nhược', BALANCED: 'trung hòa', STRONG: 'thân vượng' }, en: { WEAK: 'weak Day Master', BALANCED: 'balanced Day Master', STRONG: 'strong Day Master' } }, elementNames = (values) => values.map(value => labels.elements[ELEMENT_CODES[value]]), elementCodes = (values) => values.map(value => ELEMENT_CODES[value]);
    const dmStem = labels.stems[chart.dayMaster.code], dmElement = labels.elements[chart.dayMaster.elementCode], dayMasterStrengthCode = dmStrengthCodes[chart.pattern.dayMasterStrength];
    return { schemaVersion: '1.0', locale, engineVersion: chart.metadata.methodology.engineVersion, pillars: { year: chartPillar(chart.pillars.year, locale), month: chartPillar(chart.pillars.month, locale), day: chartPillar(chart.pillars.day, locale), hour: chartPillar(chart.pillars.hour, locale) }, dayMaster: { stemCode: chart.dayMaster.code, stem: dmStem, elementCode: chart.dayMaster.elementCode, element: dmElement, text: `${dmStem} ${dmElement}` }, elements: chart.elements.map(item => { const strengthCode = strengthCodes[item.strength]; return { elementCode: item.elementCode, element: labels.elements[item.elementCode], percent: item.percent, strengthCode, strength: strengthLabels[locale][strengthCode] }; }), activeLuck: active ? { order: active.order, startYear: active.startYear, pillar: localizedPillar(active.stem.code, active.branch.code, locale) } : null, annual: { year: chart.annualAnalysis.year, pillar: localizedPillar(chart.annual.stem.code, chart.annual.branch.code, locale), tenGodCode: chart.annualAnalysis.stemTenGodCode, tenGod: labels.tenGods[chart.annualAnalysis.stemTenGodCode] }, pattern: { primaryTenGodCode, primary: `${labels.tenGods[primaryTenGodCode]} ${locale === 'en' ? 'pattern (preliminary)' : 'cách (sơ bộ)'}`, dayMasterStrengthCode, dayMasterStrength: dmStrengthLabels[locale][dayMasterStrengthCode], favorableElementCodes: elementCodes(chart.pattern.favorableElements), favorableElements: elementNames(chart.pattern.favorableElements), unfavorableElementCodes: elementCodes(chart.pattern.unfavorableElements), unfavorableElements: elementNames(chart.pattern.unfavorableElements) }, warnings: locale === 'vi' ? [...chart.metadata.warnings] : [...new Set(chart.metadata.warnings.map(() => 'Review calculation assumptions before interpretation.'))] };
}
/** Create a compact localized view of a calculated annual timeline. */
export function localizeAnnualTimeline(timeline, locale = 'vi') {
    if (!timeline.length)
        throw new RangeError('Timeline cần ít nhất một năm');
    const labels = getCoreLabels(locale), entries = timeline.map(entry => { const annual = entry.analysis.pillar, active = entry.activeLuck.pillar; return { year: entry.year, annual: localizedPillar(annual.stem.code, annual.branch.code, locale), tenGodCode: entry.analysis.stemTenGodCode, tenGod: labels.tenGods[entry.analysis.stemTenGodCode], activeLuck: active ? { order: active.order, pillar: localizedPillar(active.stem.code, active.branch.code, locale) } : null }; });
    return { schemaVersion: '1.0', locale, fromYear: entries[0].year, toYear: entries[entries.length - 1].year, entries };
}
export function localizeFacts(chart, locale = 'vi') {
    const english = { DAY_MASTER: `Day Master is ${chart.dayMaster.name} ${chart.dayMaster.element}.`, SEASON: `Birth month is ${chart.pillars.month.branch.name}; seasonal qi favors ${chart.pillars.month.branch.element}.`, ELEMENT_BALANCE: `${[...chart.elements].sort((a, b) => b.percent - a.percent)[0].element} is the strongest element; Day Master ${chart.dayMaster.element} is ${chart.elements.find(x => x.element === chart.dayMaster.element).strength}.`, NEAR_SOLAR_TERM: `Birth time is close to a solar-term boundary; verify the input.` };
    const facts = chart.metadata.facts.map(f => ({ code: f.code, text: locale === 'vi' ? f.vi : (english[f.code] ?? f.vi), confidence: f.confidence, evidence: f.evidence }));
    return { schemaVersion: '1.0', locale, facts, warnings: locale === 'vi' ? chart.metadata.warnings : chart.metadata.warnings.map(() => 'Review the calculation warnings before interpretation.') };
}
const methodologyLabels = {
    vi: { YEAR_BOUNDARY: 'Ranh giới năm dùng Lập Xuân.', MONTH_BOUNDARY: 'Ranh giới tháng dùng 12 Tiết (Jie).', DAY_BOUNDARY: 'Ranh giới ngày đã chọn.', HOUR_BOUNDARY: 'Giờ Tý là khoảng hai giờ lấy nửa đêm làm tâm.', SOLAR_TERM_MODEL: 'Tiết khí dùng mô hình hoàng kinh Mặt Trời xấp xỉ.', TRUE_SOLAR_TIME: 'Hiệu chỉnh giờ Mặt Trời thật.', TRUE_SOLAR_TIME_MODEL: 'Mô hình hiệu chỉnh giờ Mặt Trời.', LUCK_DIRECTION: 'Chiều Đại Vận dựa trên giới tính và âm dương Can năm.', LUCK_START: 'Mốc khởi vận dùng Tiết kế tiếp theo chiều vận.', LUCK_AGE: 'Quy đổi khởi vận theo ba ngày bằng một năm.', ELEMENT_BALANCE: 'Cân bằng Ngũ Hành dùng heuristic trọng số.', PATTERN: 'Cách cục dùng heuristic khí tháng.', SHEN_SHA: 'Thần Sát dùng catalog có phiên bản.' },
    en: { YEAR_BOUNDARY: 'The year boundary uses Li Chun.', MONTH_BOUNDARY: 'Month boundaries use the twelve Jie solar terms.', DAY_BOUNDARY: 'Selected day-boundary convention.', HOUR_BOUNDARY: 'The Zi hour is a two-hour period centered on midnight.', SOLAR_TERM_MODEL: 'Solar terms use an approximate solar-longitude model.', TRUE_SOLAR_TIME: 'True solar time correction.', TRUE_SOLAR_TIME_MODEL: 'True solar time correction model.', LUCK_DIRECTION: 'Luck-cycle direction uses gender and year-stem polarity.', LUCK_START: 'Luck starts at the directional Jie boundary.', LUCK_AGE: 'Luck-start age uses three days per year.', ELEMENT_BALANCE: 'Five Element balance uses a weighted heuristic.', PATTERN: 'Pattern analysis uses a month-qi heuristic.', SHEN_SHA: 'Shen Sha uses a versioned catalog.' }
};
export function localizeMethodology(methodology, locale = 'vi') {
    const label = methodologyLabels[locale];
    const values = { YEAR_BOUNDARY: methodology.calendar.yearBoundary, MONTH_BOUNDARY: methodology.calendar.monthBoundary, DAY_BOUNDARY: methodology.calendar.dayBoundary, HOUR_BOUNDARY: methodology.calendar.hourBoundary, SOLAR_TERM_MODEL: methodology.calendar.solarTermModel, TRUE_SOLAR_TIME: methodology.trueSolarTime.enabled, TRUE_SOLAR_TIME_MODEL: methodology.trueSolarTime.model, LUCK_DIRECTION: methodology.luckCycle.directionRule, LUCK_START: methodology.luckCycle.startBoundary, LUCK_AGE: methodology.luckCycle.ageConversion, ELEMENT_BALANCE: methodology.analysis.elementBalance, PATTERN: methodology.analysis.pattern, SHEN_SHA: methodology.analysis.shenSha };
    return { schemaVersion: '1.0', locale, profileCode: methodology.profileCode, engineVersion: methodology.engineVersion, items: Object.entries(label).map(([code, text]) => ({ code, text, value: values[code] })) };
}
