import { getCoreLabels } from './localization.js';
const COLORS = { WOOD: '#238636', FIRE: '#cf222e', EARTH: '#9a6700', METAL: '#57606a', WATER: '#0969da' };
const HIGH_CONTRAST_COLORS = { WOOD: '#006b2d', FIRE: '#b00020', EARTH: '#6b4f00', METAL: '#30343b', WATER: '#0047ab' };
const escape = (s) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c]));
export function renderBaziSvg(chart, options = {}) {
    const locale = options.locale ?? 'vi', labels = getCoreLabels(locale), pillarLabels = locale === 'vi' ? { YEAR: 'Năm', MONTH: 'Tháng', DAY: 'Ngày', HOUR: 'Giờ' } : { YEAR: 'Year', MONTH: 'Month', DAY: 'Day', HOUR: 'Hour' }, dayMaster = locale === 'vi' ? 'Nhật Chủ' : 'Day Master', colors = options.highContrast ? HIGH_CONTRAST_COLORS : COLORS;
    const showBalance = options.showElementBalance !== false, width = Math.max(480, Math.min(1600, options.width ?? 720)), baseHeight = options.showHiddenStems === false ? 410 : 470, height = baseHeight + (showBalance ? 120 : 0), title = escape(options.title ?? (locale === 'vi' ? 'Lá số Bát Tự' : 'Bazi Chart'));
    const pillars = Object.values(chart.pillars), cell = (width - 80) / 4;
    const cards = pillars.map((p, i) => { const x = 40 + i * cell, god = p.tenGodCode === 'DAY_MASTER' ? dayMaster : labels.tenGods[p.tenGodCode]; const hidden = options.showHiddenStems === false ? '' : `<text x="${x + cell / 2}" y="330" class="hidden">${escape(p.branch.hiddenStems.map(h => `${labels.stems[h.code]} ${Math.round(h.weight * 100)}%`).join(' · '))}</text>`; return `<g><rect x="${x + 5}" y="95" width="${cell - 10}" height="270" rx="12" class="card"/><text x="${x + cell / 2}" y="125" class="label">${pillarLabels[p.labelCode]}</text><text x="${x + cell / 2}" y="185" class="stem" fill="${colors[p.stem.elementCode]}">${labels.stems[p.stem.code]}</text><text x="${x + cell / 2}" y="245" class="branch" fill="${colors[p.branch.elementCode]}">${labels.branches[p.branch.code]}</text><text x="${x + cell / 2}" y="280" class="god">${escape(god)}</text>${hidden}</g>`; }).join('');
    const balanceY = baseHeight - 15, balanceCell = (width - 80) / 5, balanceLabel = locale === 'vi' ? 'Cân bằng Ngũ Hành' : 'Five Element Balance';
    const balance = showBalance ? `<g class="element-balance" role="group" aria-label="${balanceLabel}"><text x="40" y="${balanceY}" class="section-title">${balanceLabel}</text>${chart.elements.map((item, i) => { const x = 40 + i * balanceCell, barWidth = Math.max(2, (balanceCell - 14) * item.percent / 100); return `<text x="${x}" y="${balanceY + 25}" class="balance-label">${labels.elements[item.elementCode]} ${item.percent}%</text><rect x="${x}" y="${balanceY + 34}" width="${balanceCell - 14}" height="12" rx="6" class="bar-bg"/><rect x="${x}" y="${balanceY + 34}" width="${barWidth}" height="12" rx="6" fill="${colors[item.elementCode]}"/>`; }).join('')}</g>` : '';
    const legend = Object.entries(colors).map(([e, c], i) => `<circle cx="${60 + i * 120}" cy="${height - 35}" r="7" fill="${c}"/><text x="${73 + i * 120}" y="${height - 30}" class="legend">${labels.elements[e]}</text>`).join('');
    const description = locale === 'vi' ? `Bốn trụ Năm, Tháng, Ngày, Giờ; Nhật Chủ ${labels.stems[chart.dayMaster.code]} ${labels.elements[chart.dayMaster.elementCode]}` : `Four Pillars: Year, Month, Day and Hour; Day Master ${labels.stems[chart.dayMaster.code]} ${labels.elements[chart.dayMaster.elementCode]}`;
    return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc" data-contrast="${options.highContrast ? 'high' : 'standard'}"><title id="title">${title}</title><desc id="desc">${escape(description)}</desc><style>.bg{fill:#fff}.card{fill:#f6f8fa;stroke:${options.highContrast ? '#000' : '#d0d7de'};stroke-width:${options.highContrast ? 2 : 1}}.title{font:700 24px system-ui;text-anchor:middle;fill:#24292f}.label,.god,.hidden,.legend,.balance-label,.section-title{font-family:system-ui;fill:${options.highContrast ? '#000' : '#57606a'}}.label,.god,.hidden{ text-anchor:middle}.label{font-size:14px;font-weight:600}.stem,.branch{font:700 34px system-ui;text-anchor:middle}.god{font-size:13px}.hidden{font-size:11px}.legend{font-size:13px}.section-title{font-size:14px;font-weight:700}.balance-label{font-size:11px}.bar-bg{fill:${options.highContrast ? '#fff' : '#eaeef2'};stroke:${options.highContrast ? '#000' : 'none'}}</style><rect class="bg" width="100%" height="100%"/><text x="${width / 2}" y="50" class="title">${title}</text>${cards}${balance}${legend}</svg>`;
}
