import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname,resolve } from 'node:path';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),cli=resolve(root,'dist/cli.js');
const valid={localDateTime:'2000-01-07T12:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'};
const run=(args,input)=>spawnSync(process.execPath,[cli,...args],{input,encoding:'utf8'});
const single=run(['--stdin','--compact'],JSON.stringify(valid));
if(single.status!==0||JSON.parse(single.stdout).pillars.day.stem.code!=='JIA')throw new Error(`stdin single failed: ${single.stderr}`);
const batch=run(['--stdin','--batch','--compact'],JSON.stringify([valid,{...valid,localDateTime:'bad'}]));
const batchResult=JSON.parse(batch.stdout);
if(batch.status!==0||batchResult.summary.succeeded!==1||batchResult.summary.failed!==1)throw new Error(`stdin batch failed: ${batch.stderr}`);
if(batchResult.items[1]?.error?.code!=='LOCAL_DATETIME_FORMAT')throw new Error('batch error code missing');
const structuredError=spawnSync(process.execPath,[cli,'--error-json','--locale','en','--facts','{bad'],{encoding:'utf8'});
const structuredErrorResult=JSON.parse(structuredError.stderr);
if(structuredError.status!==1||structuredErrorResult.code!=='INVALID_JSON'||structuredErrorResult.message!=='Invalid JSON input')throw new Error(`structured error failed: ${structuredError.stderr}`);
const timelineError=run(['--stdin','--timeline','2027:2025','--error-json','--locale','en'],JSON.stringify(valid));
if(timelineError.status!==1||JSON.parse(timelineError.stderr).code!=='TIMELINE_RANGE')throw new Error(`timeline error code failed: ${timelineError.stderr}`);
const sensitivityError=run(['--stdin','--sensitivity','0:1','--error-json','--locale','en'],JSON.stringify(valid));
if(sensitivityError.status!==1||JSON.parse(sensitivityError.stderr).code!=='SENSITIVITY_WINDOW')throw new Error(`sensitivity error code failed: ${sensitivityError.stderr}`);
const conflict=run(['--stdin',JSON.stringify(valid)],JSON.stringify(valid));
if(conflict.status!==1||!conflict.stderr.includes('không nhận thêm'))throw new Error('stdin conflict was not rejected');
const sensitivity=run(['--stdin','--sensitivity','15:5','--compact'],JSON.stringify({...valid,localDateTime:'2026-02-04T03:00:00'}));
const sensitivityResult=JSON.parse(sensitivity.stdout);
if(sensitivity.status!==0||sensitivityResult.stable!==false||sensitivityResult.sampleCount!==7)throw new Error(`stdin sensitivity failed: ${sensitivity.stderr}`);
const localizedSensitivity=run(['--stdin','--sensitivity','15:5','--locale','en','--compact'],JSON.stringify({...valid,localDateTime:'2026-02-04T03:00:00'}));
const localizedSensitivityResult=JSON.parse(localizedSensitivity.stdout);
if(localizedSensitivity.status!==0||localizedSensitivityResult.locale!=='en'||!localizedSensitivityResult.summary||!localizedSensitivityResult.variants.some(x=>x.changedPillars.includes('Month')&&x.changedPillarCodes.includes('MONTH')))throw new Error(`localized sensitivity failed: ${localizedSensitivity.stderr}`);
const capabilities=run(['--capabilities','--compact']);
const capabilitiesResult=JSON.parse(capabilities.stdout);
if(capabilities.status!==0||capabilitiesResult.offline!==true||!capabilitiesResult.features.includes('BATCH'))throw new Error(`capabilities failed: ${capabilities.stderr}`);
const compatibility=run(['--stdin','--compatibility','--compact'],JSON.stringify([valid,{...valid,localDateTime:'1988-11-02T08:10:00',gender:'female'}]));
const compatibilityResult=JSON.parse(compatibility.stdout);
if(compatibility.status!==0||compatibilityResult.schemaVersion!=='1.0'||compatibilityResult.factors.length!==4)throw new Error(`compatibility failed: ${compatibility.stderr}`);
const localizedCompatibility=run(['--stdin','--compatibility','--locale','en','--compact'],JSON.stringify([valid,{...valid,localDateTime:'1988-11-02T08:10:00',gender:'female'}]));
const localizedCompatibilityResult=JSON.parse(localizedCompatibility.stdout);
if(localizedCompatibility.status!==0||localizedCompatibilityResult.locale!=='en'||localizedCompatibilityResult.factors.length!==4||!localizedCompatibilityResult.gradeCode)throw new Error(`localized compatibility failed: ${localizedCompatibility.stderr}`);
const svg=run(['--stdin','--svg','--locale','en','--title','A < B','--no-hidden-stems','--high-contrast','--width','640'],JSON.stringify(valid));
if(svg.status!==0||!svg.stdout.startsWith('<svg')||!svg.stdout.includes('A &lt; B')||svg.stdout.includes('class="hidden"')||!svg.stdout.includes('class="element-balance"')||!svg.stdout.includes('data-contrast="high"'))throw new Error(`svg failed: ${svg.stderr}`);
const audit=run(['--stdin','--audit','--compact'],JSON.stringify(valid));
const auditResult=JSON.parse(audit.stdout);
if(audit.status!==0||auditResult.schemaVersion!=='1.0'||auditResult.rules.length<10||!auditResult.rules.some(x=>x.ruleCode==='CALENDAR_YEAR_LI_CHUN'))throw new Error(`audit failed: ${audit.stderr}`);
const localizedAudit=run(['--stdin','--audit','--locale','en','--compact'],JSON.stringify(valid));
const localizedAuditResult=JSON.parse(localizedAudit.stdout);
if(localizedAudit.status!==0||localizedAuditResult.locale!=='en'||!localizedAuditResult.rules.every(x=>x.text&&!x.descriptionVi))throw new Error(`localized audit failed: ${localizedAudit.stderr}`);
const facts=run(['--stdin','--facts','--locale','en','--compact'],JSON.stringify(valid));
if(facts.status!==0||JSON.parse(facts.stdout).locale!=='en'||!JSON.parse(facts.stdout).facts.some(x=>x.code==='DAY_MASTER'&&x.text.includes('Day Master')))throw new Error(`facts failed: ${facts.stderr}`);
const methodology=run(['--stdin','--methodology','--locale','en','--compact'],JSON.stringify(valid));
const methodologyResult=JSON.parse(methodology.stdout);
if(methodology.status!==0||methodologyResult.locale!=='en'||methodologyResult.items.length!==13||methodologyResult.items[0]?.code!=='YEAR_BOUNDARY')throw new Error(`methodology failed: ${methodology.stderr}`);
const summary=run(['--stdin','--summary','--locale','en','--compact'],JSON.stringify(valid));
const summaryResult=JSON.parse(summary.stdout);
if(summary.status!==0||summaryResult.locale!=='en'||summaryResult.pillars.day.stemCode!=='JIA'||summaryResult.elements.length!==5||!summaryResult.pattern.primaryTenGodCode)throw new Error(`localized summary failed: ${summary.stderr}`);
const localizedTimeline=run(['--stdin','--timeline','2025:2027','--locale','en','--compact'],JSON.stringify(valid));
const localizedTimelineResult=JSON.parse(localizedTimeline.stdout);
if(localizedTimeline.status!==0||localizedTimelineResult.locale!=='en'||localizedTimelineResult.entries.length!==3||localizedTimelineResult.entries[0].annual.stem==='Giáp')throw new Error(`localized timeline failed: ${localizedTimeline.stderr}`);
console.log(JSON.stringify({stdinSingle:true,stdinBatch:true,structuredErrors:true,stdinSensitivity:true,localizedSensitivity:true,compatibility:true,localizedCompatibility:true,svg:true,audit:true,localizedAudit:true,summary:true,facts:true,methodology:true,localizedTimeline:true,capabilities:true,conflictRejected:true}));
