import { calculateBazi, renderBaziSvg } from '../dist/index.js';

const form=document.querySelector('#birth-form'),status=document.querySelector('#status'),chart=document.querySelector('#chart'),output=document.querySelector('#output'),svgButton=document.querySelector('#download-svg'),jsonButton=document.querySelector('#download-json');
let latestSvg='',latestJson='';
const download=(name,content,type)=>{const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);};
form.addEventListener('submit',event=>{event.preventDefault();try{const trueSolarTime=document.querySelector('#trueSolarTime').checked,city=document.querySelector('#city').value.trim();const input={localDateTime:document.querySelector('#localDateTime').value+':00',timezoneOffsetMinutes:Number(document.querySelector('#timezoneOffsetMinutes').value),asOfYear:Number(document.querySelector('#asOfYear').value),gender:document.querySelector('#gender').value,trueSolarTime,...(trueSolarTime?{location:{city}}:{})};const result=calculateBazi(input);latestSvg=renderBaziSvg(result,{width:900,highContrast:true});latestJson=JSON.stringify(result,null,2);chart.innerHTML=latestSvg;output.textContent=latestJson;const boundary=result.normalized.solarTerms;status.className=boundary.nearBoundary?'warning':'success';status.textContent=boundary.nearBoundary?`Cảnh báo: giờ sinh cách ranh Tiết khí khoảng ${boundary.nearestDistanceMinutes} phút.`:'Đã tính xong hoàn toàn offline.';svgButton.disabled=jsonButton.disabled=false;}catch(error){status.className='error';status.textContent=error instanceof Error?error.message:String(error);chart.replaceChildren();output.textContent='';svgButton.disabled=jsonButton.disabled=true;}});
svgButton.addEventListener('click',()=>download('viet-bazi-chart.svg',latestSvg,'image/svg+xml'));
jsonButton.addEventListener('click',()=>download('viet-bazi-result.json',latestJson,'application/json'));
form.requestSubmit();
