import { calculateAnnualTimeline, calculateBazi, renderBaziSvg, VIETNAM_CITIES } from '../dist/index.js';

const form=document.querySelector('#birth-form'),status=document.querySelector('#status'),summary=document.querySelector('#summary'),timelineBody=document.querySelector('#timeline'),chart=document.querySelector('#chart'),output=document.querySelector('#output'),svgButton=document.querySelector('#download-svg'),jsonButton=document.querySelector('#download-json');
let latestSvg='',latestJson='';
const citySelect=document.querySelector('#city');for(const city of VIETNAM_CITIES){const option=document.createElement('option');option.value=city.id;option.textContent=city.name;if(city.id==='ha-noi')option.selected=true;citySelect.append(option);}
const download=(name,content,type)=>{const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);};
const renderSummary=result=>{const active=result.luck.active.pillar,items=[['Nhật Chủ',`${result.dayMaster.name} ${result.dayMaster.element}`],['Lưu Niên',`${result.annual.stem.name} ${result.annual.branch.name} (${result.annualAnalysis.year})`],['Đại Vận',active?`${active.stem.name} ${active.branch.name} · ${active.startYear}–${active.startYear+9}`:'Chưa vào Đại Vận'],['Cách cục',result.pattern.primary]];summary.replaceChildren(...items.map(([label,value])=>{const card=document.createElement('article'),heading=document.createElement('strong'),text=document.createElement('span');heading.textContent=label;text.textContent=value;card.append(heading,text);return card;}));};
const renderTimeline=result=>{const year=result.input.asOfYear,entries=calculateAnnualTimeline(result,Math.max(1600,year-2),Math.min(2400,year+2));timelineBody.replaceChildren(...entries.map(entry=>{const row=document.createElement('tr'),annual=entry.analysis.pillar,active=entry.activeLuck.pillar;for(const value of [entry.year,`${annual.stem.name} ${annual.branch.name}`,entry.analysis.stemTenGod,active?`${active.stem.name} ${active.branch.name}`:'—']){const cell=document.createElement('td');cell.textContent=String(value);row.append(cell);}if(entry.year===year)row.className='current-year';return row;}));};
form.addEventListener('submit',event=>{event.preventDefault();try{const trueSolarTime=document.querySelector('#trueSolarTime').checked,city=document.querySelector('#city').value;const input={localDateTime:document.querySelector('#localDateTime').value+':00',timezoneOffsetMinutes:Number(document.querySelector('#timezoneOffsetMinutes').value),asOfYear:Number(document.querySelector('#asOfYear').value),gender:document.querySelector('#gender').value,dayBoundary:document.querySelector('#dayBoundary').value,trueSolarTime,...(trueSolarTime?{location:{city}}:{})};const result=calculateBazi(input);latestSvg=renderBaziSvg(result,{width:900,highContrast:true,locale:document.querySelector('#locale').value});latestJson=JSON.stringify(result,null,2);chart.innerHTML=latestSvg;output.textContent=latestJson;renderSummary(result);renderTimeline(result);const boundary=result.normalized.solarTerms;status.className=boundary.nearBoundary?'warning':'success';status.textContent=boundary.nearBoundary?`Cảnh báo: giờ sinh cách ranh Tiết khí khoảng ${boundary.nearestDistanceMinutes} phút.`:'Đã tính xong hoàn toàn offline.';svgButton.disabled=jsonButton.disabled=false;}catch(error){status.className='error';status.textContent=error instanceof Error?error.message:String(error);chart.replaceChildren();summary.replaceChildren();timelineBody.replaceChildren();output.textContent='';svgButton.disabled=jsonButton.disabled=true;}});
svgButton.addEventListener('click',()=>download('viet-bazi-chart.svg',latestSvg,'image/svg+xml'));
jsonButton.addEventListener('click',()=>download('viet-bazi-result.json',latestJson,'application/json'));
form.requestSubmit();
if('serviceWorker' in navigator)navigator.serviceWorker.register('../service-worker.js',{scope:'../'}).catch(error=>{console.warn('Không thể bật offline cache:',error);});
