import type { BranchCode, ElementCode, RelationTypeCode, ShenShaCode, StemCode, TenGodCode } from './types.js';

export type CoreLocale='vi'|'en';
export interface CoreLabels {stems:Record<StemCode,string>;branches:Record<BranchCode,string>;elements:Record<ElementCode,string>;tenGods:Record<TenGodCode,string>;relations:Record<RelationTypeCode,string>;shenSha:Record<ShenShaCode,string>}
const relationVi:Record<RelationTypeCode,string>={LIU_HE:'Lục hợp',LIU_CHONG:'Lục xung',LIU_HAI:'Lục hại',LIU_PO:'Lục phá',ZI_XING:'Tự hình',SAN_XING:'Tam hình',SAN_HE:'Tam hợp',SAN_HUI:'Tam hội'};
const relationEn:Record<RelationTypeCode,string>={LIU_HE:'Six Combination',LIU_CHONG:'Six Clash',LIU_HAI:'Six Harm',LIU_PO:'Six Destruction',ZI_XING:'Self Punishment',SAN_XING:'Three Punishments',SAN_HE:'Three Harmony',SAN_HUI:'Seasonal Combination'};
const shenShaVi:Record<ShenShaCode,string>={TIAN_YI_GUI_REN:'Thiên Ất Quý Nhân',TAI_JI_GUI_REN:'Thái Cực Quý Nhân',WEN_CHANG:'Văn Xương',LU_SHEN:'Lộc Thần',YANG_REN:'Dương Nhận',JIN_YU:'Kim Dư',GUO_YIN:'Quốc Ấn',XUE_TANG:'Học Đường',TAO_HUA:'Đào Hoa',HONG_LUAN:'Hồng Loan',TIAN_XI:'Thiên Hỷ',YI_MA:'Dịch Mã',HUA_GAI:'Hoa Cái',JIANG_XING:'Tướng Tinh',JIE_SHA:'Kiếp Sát',WANG_SHEN:'Vong Thần',ZAI_SHA:'Tai Sát',GU_SHEN:'Cô Thần',GUA_SU:'Quả Tú',TIAN_YI:'Thiên Y',TIAN_LUO:'Thiên La',DI_WANG:'Địa Võng',TIAN_SHE:'Thiên Xá'};
const shenShaEn:Record<ShenShaCode,string>={TIAN_YI_GUI_REN:'Heavenly Noble',TAI_JI_GUI_REN:'Supreme Ultimate Noble',WEN_CHANG:'Academic Star',LU_SHEN:'Prosperity Star',YANG_REN:'Yang Blade',JIN_YU:'Golden Carriage',GUO_YIN:'National Seal',XUE_TANG:'Academic Hall',TAO_HUA:'Peach Blossom',HONG_LUAN:'Red Matchmaker',TIAN_XI:'Heavenly Joy',YI_MA:'Traveling Horse',HUA_GAI:'Canopy Star',JIANG_XING:'General Star',JIE_SHA:'Robbery Sha',WANG_SHEN:'Loss Spirit',ZAI_SHA:'Disaster Sha',GU_SHEN:'Solitary Star',GUA_SU:'Widow Star',TIAN_YI:'Heavenly Doctor',TIAN_LUO:'Heavenly Net',DI_WANG:'Earthly Net',TIAN_SHE:'Heavenly Pardon'};
const vi:CoreLabels={stems:{JIA:'Giáp',YI:'Ất',BING:'Bính',DING:'Đinh',WU:'Mậu',JI:'Kỷ',GENG:'Canh',XIN:'Tân',REN:'Nhâm',GUI:'Quý'},branches:{ZI:'Tý',CHOU:'Sửu',YIN:'Dần',MAO:'Mão',CHEN:'Thìn',SI:'Tỵ',WU:'Ngọ',WEI:'Mùi',SHEN:'Thân',YOU:'Dậu',XU:'Tuất',HAI:'Hợi'},elements:{WOOD:'Mộc',FIRE:'Hỏa',EARTH:'Thổ',METAL:'Kim',WATER:'Thủy'},tenGods:{BI_JIAN:'Tỷ Kiên',JIE_CAI:'Kiếp Tài',SHI_SHEN:'Thực Thần',SHANG_GUAN:'Thương Quan',PIAN_CAI:'Thiên Tài',ZHENG_CAI:'Chính Tài',QI_SHA:'Thất Sát',ZHENG_GUAN:'Chính Quan',PIAN_YIN:'Thiên Ấn',ZHENG_YIN:'Chính Ấn'},relations:relationVi,shenSha:shenShaVi};
const en:CoreLabels={stems:{JIA:'Jia',YI:'Yi',BING:'Bing',DING:'Ding',WU:'Wu',JI:'Ji',GENG:'Geng',XIN:'Xin',REN:'Ren',GUI:'Gui'},branches:{ZI:'Rat',CHOU:'Ox',YIN:'Tiger',MAO:'Rabbit',CHEN:'Dragon',SI:'Snake',WU:'Horse',WEI:'Goat',SHEN:'Monkey',YOU:'Rooster',XU:'Dog',HAI:'Pig'},elements:{WOOD:'Wood',FIRE:'Fire',EARTH:'Earth',METAL:'Metal',WATER:'Water'},tenGods:{BI_JIAN:'Friend',JIE_CAI:'Rob Wealth',SHI_SHEN:'Eating God',SHANG_GUAN:'Hurting Officer',PIAN_CAI:'Indirect Wealth',ZHENG_CAI:'Direct Wealth',QI_SHA:'Seven Killings',ZHENG_GUAN:'Direct Officer',PIAN_YIN:'Indirect Resource',ZHENG_YIN:'Direct Resource'},relations:relationEn,shenSha:shenShaEn};
export function getCoreLabels(locale:CoreLocale):CoreLabels{return locale==='vi'?vi:en;}
