import { describe,expect,it } from 'vitest';
import { calculateAnnualTimeline,calculateBazi } from './engine.js';
import { compareBaziCharts,compareBirthInputs,localizeCompatibility } from './compatibility.js';
import { compareBirthInputsFromJson,renderBaziSvgFromJson } from './json.js';
import { renderBaziSvg } from './svg.js';
import { localizeAnnualTimeline,localizeChartSummary,localizeFacts,localizeMethodology } from './localization-report.js';

const a=calculateBazi({localDateTime:'1990-05-17T14:30:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'female'});
const b=calculateBazi({localDateTime:'1988-11-02T08:10:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'});

describe('phase 2 building blocks',()=>{
  it('returns a bounded, explainable compatibility score',()=>{const r=compareBaziCharts(a,b);expect(r.schemaVersion).toBe('1.0');expect(r.score).toBeGreaterThanOrEqual(0);expect(r.score).toBeLessThanOrEqual(100);expect(r.factors.reduce((n,f)=>n+f.score,0)).toBe(r.score);expect(r.metadata.methodology).toBe('heuristic-v1');});
  it('compares typed and JSON birth-input pairs',()=>{const inputs=[a.input,b.input] as const;expect(compareBirthInputs(...inputs)).toEqual(compareBaziCharts(a,b));expect(compareBirthInputsFromJson(JSON.stringify(inputs))).toEqual(compareBaziCharts(a,b));expect(()=>compareBirthInputsFromJson(JSON.stringify([a.input]))).toThrow('đúng 2');});
  it('localizes compatibility without changing stable scores or evidence',()=>{const raw=compareBaziCharts(a,b),en=localizeCompatibility(raw,'en'),vi=localizeCompatibility(raw,'vi');expect(en.gradeCode).toBe(vi.gradeCode);expect(en.factors.map(x=>[x.code,x.score,x.evidence])).toEqual(vi.factors.map(x=>[x.code,x.score,x.evidence]));expect(en.factors[0]?.text).not.toBe(vi.factors[0]?.text);expect(en.warning).toContain('heuristic');});
  it('renders standalone accessible SVG and escapes title',()=>{const svg=renderBaziSvg(a,{title:'A < B & C'});expect(svg).toContain('<svg');expect(svg).toContain('A &lt; B &amp; C');expect(svg).toContain('aria-labelledby');expect(svg).not.toContain('A < B');});
  it('renders deterministic element balance bars and high-contrast palette',()=>{const svg=renderBaziSvg(a,{locale:'en',highContrast:true});expect(svg).toContain('class="element-balance"');expect(svg).toContain('Five Element Balance');expect(svg).toContain('data-contrast="high"');expect(svg).toContain(`${a.elements[0]!.percent}%`);expect(renderBaziSvg(a,{showElementBalance:false})).not.toContain('class="element-balance"');});
  it('renders a fully localized English SVG view',()=>{const svg=renderBaziSvg(a,{locale:'en'});expect(svg).toContain('Bazi Chart');expect(svg).toContain('Day Master');expect(svg).toContain('Four Pillars');expect(svg).not.toContain('Nhật Chủ');});
  it('localizes metadata facts without changing stable codes',()=>{const report=localizeFacts(a,'en');expect(report.locale).toBe('en');expect(report.facts.find(x=>x.code==='DAY_MASTER')?.text).toContain('Day Master');expect(report.facts.find(x=>x.code==='DAY_MASTER')?.evidence).toEqual(['pillars.day.stem']);});
  it('localizes methodology descriptions without changing convention values',()=>{const en=localizeMethodology(a.metadata.methodology,'en'),vi=localizeMethodology(a.metadata.methodology,'vi');expect(en.items.map(x=>x.code)).toEqual(vi.items.map(x=>x.code));expect(en.items.map(x=>x.value)).toEqual(vi.items.map(x=>x.value));expect(en.items[0]?.text).not.toBe(vi.items[0]?.text);});
  it('localizes annual timeline labels without changing stable codes',()=>{const timeline=calculateAnnualTimeline(a,2025,2027),en=localizeAnnualTimeline(timeline,'en'),vi=localizeAnnualTimeline(timeline,'vi');expect(en.entries.map(x=>[x.year,x.annual.stemCode,x.annual.branchCode,x.tenGodCode,x.activeLuck?.order])).toEqual(vi.entries.map(x=>[x.year,x.annual.stemCode,x.annual.branchCode,x.tenGodCode,x.activeLuck?.order]));expect(en.entries[0]?.annual.text).not.toBe(vi.entries[0]?.annual.text);expect(en).toMatchObject({schemaVersion:'1.0',locale:'en',fromYear:2025,toYear:2027});});
  it('builds localized chart summaries with stable machine codes',()=>{const en=localizeChartSummary(a,'en'),vi=localizeChartSummary(a,'vi');expect(en.pillars.year.stemCode).toBe(vi.pillars.year.stemCode);expect(en.dayMaster.stemCode).toBe(vi.dayMaster.stemCode);expect(en.elements.map(x=>x.elementCode)).toEqual(vi.elements.map(x=>x.elementCode));expect(en.dayMaster.text).not.toBe(vi.dayMaster.text);expect(en.pattern.primaryTenGodCode).toBe(a.pillars.month.branch.hiddenStems[0]?.tenGodCode);});
  it('renders SVG from an untyped JSON boundary',()=>{const svg=renderBaziSvgFromJson(JSON.stringify(a.input),{locale:'en',title:'A < B',showHiddenStems:false});expect(svg).toContain('A &lt; B');expect(svg).not.toContain('class="hidden"');});
});
