import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import { describe,expect,it } from 'vitest';
import { calculateAnnualTimeline,calculateBazi } from './engine.js';
import { calculateBaziBatch } from './json.js';
import { localizeAnnualTimeline,localizeChartSummary,localizeFacts,localizeMethodology } from './localization-report.js';
import { createBaziAuditReport,localizeBaziAuditReport } from './traceability.js';
import { analyzeBirthTimeSensitivity,localizeBirthTimeSensitivity } from './sensitivity.js';
import { compareBirthInputs,localizeCompatibility } from './compatibility.js';
import { ANNUAL_TIMELINE_JSON_SCHEMA,BAZI_BATCH_INPUT_JSON_SCHEMA,BAZI_BATCH_RESULT_JSON_SCHEMA,BAZI_RESULT_JSON_SCHEMA,BIRTH_INPUT_JSON_SCHEMA,BIRTH_TIME_SENSITIVITY_JSON_SCHEMA,COMPATIBILITY_INPUT_JSON_SCHEMA,COMPATIBILITY_RESULT_JSON_SCHEMA,LOCALIZED_ANNUAL_TIMELINE_JSON_SCHEMA,LOCALIZED_AUDIT_REPORT_JSON_SCHEMA,LOCALIZED_BIRTH_TIME_SENSITIVITY_JSON_SCHEMA,LOCALIZED_CHART_SUMMARY_JSON_SCHEMA,LOCALIZED_COMPATIBILITY_REPORT_JSON_SCHEMA,LOCALIZED_FACTS_REPORT_JSON_SCHEMA,LOCALIZED_METHODOLOGY_REPORT_JSON_SCHEMA } from './schema.js';

describe('public JSON schemas',()=>{
  const ajv=new Ajv2020({allErrors:true,strict:false});addFormats(ajv);
  it('accepts a valid input and rejects incomplete context or location',()=>{const validate=ajv.compile(BIRTH_INPUT_JSON_SCHEMA),base={localDateTime:'2000-01-07T12:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'};expect(validate(base)).toBe(true);expect(validate({...base,asOfYear:undefined})).toBe(false);expect(validate({...base,trueSolarTime:true})).toBe(false);expect(validate({...base,location:{city:'Hà Nội',latitude:21}})).toBe(false);expect(validate({...base,unknown:true})).toBe(false);});
  it('validates a complete engine result',()=>{const result=calculateBazi({localDateTime:'1990-05-17T14:30:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'female',trueSolarTime:true,location:{city:'Hà Nội'}});const validate=ajv.compile(BAZI_RESULT_JSON_SCHEMA);expect(validate(result),JSON.stringify(validate.errors)).toBe(true);});
  it('validates batch input and both output item variants',()=>{const valid={localDateTime:'2000-01-07T12:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'},batchAjv=new Ajv2020({allErrors:true,strict:false});addFormats(batchAjv);batchAjv.addSchema(BIRTH_INPUT_JSON_SCHEMA).addSchema(BAZI_RESULT_JSON_SCHEMA);const validateInput=batchAjv.compile(BAZI_BATCH_INPUT_JSON_SCHEMA),validateResult=batchAjv.compile(BAZI_BATCH_RESULT_JSON_SCHEMA);expect(validateInput([valid])).toBe(true);expect(validateInput(Array.from({length:1001},()=>valid))).toBe(false);const result=calculateBaziBatch([valid,{...valid,gender:'invalid'}]);expect(validateResult(result),JSON.stringify(validateResult.errors)).toBe(true);const malformed={...result,items:[{index:0,ok:true,error:{name:'Error',message:'mixed shape'}}]};expect(validateResult(malformed)).toBe(false);});
  it('validates stable and changing sensitivity contracts',()=>{const validate=ajv.compile(BIRTH_TIME_SENSITIVITY_JSON_SCHEMA),input={localDateTime:'2026-02-04T03:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male' as const},changing=analyzeBirthTimeSensitivity(input,15,5),stable=analyzeBirthTimeSensitivity({...input,localDateTime:'2000-01-07T12:30:00'},20,5);expect(validate(changing),JSON.stringify(validate.errors)).toBe(true);expect(validate(stable),JSON.stringify(validate.errors)).toBe(true);expect(validate({...stable,stable:false})).toBe(false);expect(validate({...changing,variants:[{...changing.variants[0],pillars:{...changing.variants[0]?.pillars,hour:'INVALID'}}]})).toBe(false);});
  it('validates localized sensitivity reports',()=>{const raw=analyzeBirthTimeSensitivity({localDateTime:'2026-02-04T03:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'},15,5),report=localizeBirthTimeSensitivity(raw,'en'),validate=ajv.compile(LOCALIZED_BIRTH_TIME_SENSITIVITY_JSON_SCHEMA);expect(validate(report),JSON.stringify(validate.errors)).toBe(true);expect(validate({...report,locale:'fr'})).toBe(false);expect(validate({...report,summary:''})).toBe(false);});
  it('validates compatibility input and result',()=>{const first={localDateTime:'1990-05-17T14:30:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'female' as const},second={localDateTime:'1988-11-02T08:10:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male' as const},compatAjv=new Ajv2020({allErrors:true,strict:false});compatAjv.addSchema(BIRTH_INPUT_JSON_SCHEMA);const validateInput=compatAjv.compile(COMPATIBILITY_INPUT_JSON_SCHEMA),validateResult=compatAjv.compile(COMPATIBILITY_RESULT_JSON_SCHEMA),result=compareBirthInputs(first,second);expect(validateInput([first,second])).toBe(true);expect(validateInput([first])).toBe(false);expect(validateResult(result),JSON.stringify(validateResult.errors)).toBe(true);expect(validateResult({...result,score:101})).toBe(false);});
  it('validates localized compatibility reports',()=>{const first=calculateBazi({localDateTime:'1990-05-17T14:30:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'female'}),second=calculateBazi({localDateTime:'1988-11-02T08:10:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'}),report=localizeCompatibility(compareBirthInputs(first.input,second.input),'en'),validate=ajv.compile(LOCALIZED_COMPATIBILITY_REPORT_JSON_SCHEMA);expect(validate(report),JSON.stringify(validate.errors)).toBe(true);expect(validate({...report,gradeCode:'GREAT'})).toBe(false);});
  it('validates localized facts reports',()=>{const chart=calculateBazi({localDateTime:'2000-01-07T12:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'}),validate=ajv.compile(LOCALIZED_FACTS_REPORT_JSON_SCHEMA),report=localizeFacts(chart,'en');expect(validate(report),JSON.stringify(validate.errors)).toBe(true);expect(validate({...report,locale:'fr'})).toBe(false);});
  it('validates localized chart summaries',()=>{const chart=calculateBazi({localDateTime:'2000-01-07T12:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'}),report=localizeChartSummary(chart,'en'),validate=ajv.compile(LOCALIZED_CHART_SUMMARY_JSON_SCHEMA);expect(validate(report),JSON.stringify(validate.errors)).toBe(true);expect(validate({...report,locale:'fr'})).toBe(false);expect(validate({...report,elements:report.elements.slice(1)})).toBe(false);});
  it('validates localized audit reports',()=>{const chart=calculateBazi({localDateTime:'2000-01-07T12:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'}),validate=ajv.compile(LOCALIZED_AUDIT_REPORT_JSON_SCHEMA),report=localizeBaziAuditReport(createBaziAuditReport(chart),'en');expect(validate(report),JSON.stringify(validate.errors)).toBe(true);expect(validate({...report,locale:'fr'})).toBe(false);});
  it('validates localized methodology reports',()=>{const chart=calculateBazi({localDateTime:'2000-01-07T23:30:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male',dayBoundary:'midnight'}),validate=ajv.compile(LOCALIZED_METHODOLOGY_REPORT_JSON_SCHEMA),report=localizeMethodology(chart.metadata.methodology,'en');expect(validate(report),JSON.stringify(validate.errors)).toBe(true);expect(report.items.find(item=>item.code==='DAY_BOUNDARY')).toMatchObject({value:'MIDNIGHT'});expect(validate({...report,items:report.items.slice(1)})).toBe(false);});
  it('validates annual timeline bounds and structure',()=>{const chart=calculateBazi({localDateTime:'2000-01-07T12:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'}),timeline=calculateAnnualTimeline(chart,2025,2027),validate=ajv.compile(ANNUAL_TIMELINE_JSON_SCHEMA);expect(validate(timeline),JSON.stringify(validate.errors)).toBe(true);expect(validate([])).toBe(false);expect(validate([{...timeline[0],year:2500}])).toBe(false);});
  it('validates localized annual timeline reports',()=>{const chart=calculateBazi({localDateTime:'2000-01-07T12:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'}),report=localizeAnnualTimeline(calculateAnnualTimeline(chart,2025,2027),'en'),validate=ajv.compile(LOCALIZED_ANNUAL_TIMELINE_JSON_SCHEMA);expect(validate(report),JSON.stringify(validate.errors)).toBe(true);expect(validate({...report,locale:'fr'})).toBe(false);expect(validate({...report,entries:[]})).toBe(false);});
});
