import { describe,expect,it } from 'vitest';
import { analyzeBirthTimeSensitivity,localizeBirthTimeSensitivity } from './sensitivity.js';

describe('birth-time sensitivity',()=>{
  it('finds pillar changes around a solar-term boundary',()=>{const result=analyzeBirthTimeSensitivity({localDateTime:'2026-02-04T03:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'},15,5);expect(result.stable).toBe(false);expect(result.variants.some(x=>x.changedPillars.includes('YEAR'))).toBe(true);expect(result.variants.some(x=>x.changedPillars.includes('MONTH'))).toBe(true);expect(result.sampleCount).toBe(7);});
  it('reports a stable interval away from all pillar boundaries',()=>{const result=analyzeBirthTimeSensitivity({localDateTime:'2000-01-07T12:30:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'},20,5);expect(result.stable).toBe(true);expect(result.variants).toHaveLength(1);expect(result.variants[0]?.changedPillars).toEqual([]);});
  it('bounds sampling cost',()=>{const input={localDateTime:'2000-01-07T12:30:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male' as const};expect(()=>analyzeBirthTimeSensitivity(input,720,1)).toThrow('289');expect(()=>analyzeBirthTimeSensitivity(input,0,1)).toThrow('windowMinutes');});
  it('localizes explanations while preserving stable pillar codes',()=>{const raw=analyzeBirthTimeSensitivity({localDateTime:'2026-02-04T03:00:00',timezoneOffsetMinutes:420,asOfYear:2026,gender:'male'},15,5),vi=localizeBirthTimeSensitivity(raw),en=localizeBirthTimeSensitivity(raw,'en');expect(en.summary).not.toBe(vi.summary);expect(en.variants.map(x=>x.changedPillarCodes)).toEqual(vi.variants.map(x=>x.changedPillarCodes));expect(en.variants.find(x=>x.changedPillarCodes.includes('MONTH'))?.changedPillars).toContain('Month');expect(en.baseline).toEqual(raw.baseline);});
});
