import { getCoreLabels } from './localization.js';
import type { BaziResult, ElementCode, SvgOptions } from './types.js';

const COLORS:Record<ElementCode,string>={WOOD:'#238636',FIRE:'#cf222e',EARTH:'#9a6700',METAL:'#57606a',WATER:'#0969da'};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));

export function renderBaziSvg(chart:BaziResult,options:SvgOptions={}):string {
  const locale=options.locale??'vi',labels=getCoreLabels(locale),pillarLabels=locale==='vi'?{YEAR:'Năm',MONTH:'Tháng',DAY:'Ngày',HOUR:'Giờ'}:{YEAR:'Year',MONTH:'Month',DAY:'Day',HOUR:'Hour'},dayMaster=locale==='vi'?'Nhật Chủ':'Day Master';
  const width=Math.max(480,Math.min(1600,options.width??720)),height=options.showHiddenStems===false?410:470,title=escape(options.title??(locale==='vi'?'Lá số Bát Tự':'Bazi Chart'));
  const pillars=Object.values(chart.pillars),cell=(width-80)/4;
  const cards=pillars.map((p,i)=>{const x=40+i*cell,god=p.tenGodCode==='DAY_MASTER'?dayMaster:labels.tenGods[p.tenGodCode];const hidden=options.showHiddenStems===false?'':`<text x="${x+cell/2}" y="330" class="hidden">${escape(p.branch.hiddenStems.map(h=>`${labels.stems[h.code]} ${Math.round(h.weight*100)}%`).join(' · '))}</text>`;return `<g><rect x="${x+5}" y="95" width="${cell-10}" height="270" rx="12" class="card"/><text x="${x+cell/2}" y="125" class="label">${pillarLabels[p.labelCode]}</text><text x="${x+cell/2}" y="185" class="stem" fill="${COLORS[p.stem.elementCode]}">${labels.stems[p.stem.code]}</text><text x="${x+cell/2}" y="245" class="branch" fill="${COLORS[p.branch.elementCode]}">${labels.branches[p.branch.code]}</text><text x="${x+cell/2}" y="280" class="god">${escape(god)}</text>${hidden}</g>`;}).join('');
  const legend=(Object.entries(COLORS) as [ElementCode,string][]).map(([e,c],i)=>`<circle cx="${60+i*120}" cy="${height-35}" r="7" fill="${c}"/><text x="${73+i*120}" y="${height-30}" class="legend">${labels.elements[e]}</text>`).join('');
  const description=locale==='vi'?`Bốn trụ Năm, Tháng, Ngày, Giờ; Nhật Chủ ${labels.stems[chart.dayMaster.code]} ${labels.elements[chart.dayMaster.elementCode]}`:`Four Pillars: Year, Month, Day and Hour; Day Master ${labels.stems[chart.dayMaster.code]} ${labels.elements[chart.dayMaster.elementCode]}`;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc"><title id="title">${title}</title><desc id="desc">${escape(description)}</desc><style>.bg{fill:#fff}.card{fill:#f6f8fa;stroke:#d0d7de}.title{font:700 24px system-ui;text-anchor:middle;fill:#24292f}.label,.god,.hidden,.legend{font-family:system-ui;fill:#57606a;text-anchor:middle}.label{font-size:14px;font-weight:600}.stem,.branch{font:700 34px system-ui;text-anchor:middle}.god{font-size:13px}.hidden{font-size:11px}.legend{font-size:13px;text-anchor:start}</style><rect class="bg" width="100%" height="100%"/><text x="${width/2}" y="50" class="title">${title}</text>${cards}${legend}</svg>`;
}
